### ISSUE TITLE
testing & some ideas for improvement.

### ISSUE THREAD

**Issue by xrayer** [jhhoward/MicroWeb#2]
Hi, I like this attempt of makink a tiny browser. I find it usefull to run on my HP 200LX handheld PC that use 80186 and monochrome CGA with a few gray levels. I tested it and it runs at decent speed. I'm missing what key to use to follow/open selected link. I also found that monospace font is rendered cca 2x big as default font.
And please could you add some basic handling of national diacritic characters? I don't think it's necessary to support all strange diacritic fonts but I'd like just a simple mapping table that let transorm national code page (ASCII chars from 128-255 range) to basic page (0-127) according to "charset" parameter in [META HTTP-EQUIV] tag of header. This would greatly improve readability insted of seeing a lot of "?" chars. For simplicity the mapping tables could be hardcoded in some header file, I would fill the data in for CP1250.

**Comment by jhhoward** [comment]
Hi! I've tested on an HP 100LX which is very similar to the 200LX. If you are using keyboard controls then you can use tab/shift+tab to cycle through the available links and press enter to select.

There currently is no monospace font support - there are three sizes of font, which is chosen based on the HTML tag or font-size. Let me know if there is a website that you think is using the wrong font size.

For the different character sets: currently there is a very basic UTF-8 encoding support where it tries to map to the basic Latin characters as you described. I could look into the extended ASCII character set too. Do you have a website in mind that I could test with?

**Comment by xrayer** [comment]
Hi, you can test on my homepage e.g.
http://rayer.g6.cz/elektro/indesit.htm
at the bottom of page there's a big table with monospace text - [pre] tag that is rendered cca 2x bigger than other text even there's [FONT SIZE="-1"]
I don't use UTF-8 but CP1250 for central Europe.

**Comment by cml37** [comment]
@jhhoward this is a great project!  Looking forward to the progress on it.  Looks like FreeDos picked it up on Twitter!  I'd love to feature a review of this on my YouTube channel as well.  I've been writing some MS-DOS based programs of late as well!

**Comment by jhhoward** [comment]
@xrayer Thank you supplying your test case. I've added additional text encoding support that maps to the closest Latin character when possible. I've also fixed the font size and added a monospace font.
I've uploaded a new binary with the v0.4 release

**Comment by xrayer** [comment]
Thanks, now it looks much better :)
But I still have a problem to open local links via Enter (just a quick test done under WinXP) - when the link points to a local file, e.g. "dir1/dir2/file1.htm" it does nothing instad loading a local file from disk. Links with leading http:// are going to open. This feature should be implemented (if not a bug on my side) for offline reading.

**Comment by jhhoward** [comment]
Looks like there is a bug with relative link parsing. I will look into it.

**Comment by xrayer** [comment]
Hi, I tested ver. 0.5 on 200LX in offline mode and now it displays message:
Need to set MTCPCFG env var.
Failed in ParseEnv()
Please could you modify it that when env. var is not found it will just open the local file without this message as works in ver 0.4 and older?

**Comment by xrayer** [comment]
Hm, intersting that when I use force CGA -c option then I don't get this MTCPCFG message.
I also found a bug in rendering. The web page contained some partial horizontal line and when I scrolled down the horizontal line was drawn over the top URL bar. It shouldn't be never overdrawn by any page content. You can see it here:
http://rayer.g6.cz/1tmp/microweb.jpg
Also please could you add commandline option for display inversion? On 200LX need to press F2 to get normal look.

**Comment by jhhoward** [comment]
Can you provide a copy of the HTML file where the rendering bug occurred?

I can also look into the other issues

**Comment by xrayer** [comment]
Here is the exact HTML file for offline:
http://rayer.g6.cz/1tmp/EB.ZIP
I cannot reproduce the bug on Windows PC just 200LX...

**Comment by ishotjr** [comment]
I've been using this glorious program on an HP 200LX for the past week, and mostly just wanted to subscribe to this thread to watch Palmtop support evolve, but, is it possible to specify inverted CGA from the command line? I can't seem to use -c and -i at the same time? :bowtie:

**Comment by jhhoward** [comment]
For the 200LX you should be able to just run with -i to invert the screen and it will autodetect the CGA display

**Comment by jhhoward** [comment]
Just released version 2.0 which makes several improvements including better Unicode support, automatic detection of HP palmtops with a special video mode, etc. Going to close this issue as I think these have all now been addressed.
